### PR TITLE
run autoprefix before asset fingerprinting

### PR DESCRIPTION
**Pull request by cbrevdev**
Ember addon dependency to run before broccoli-asset-rev.

Addressing https://github.com/kimroen/ember-cli-autoprefixer/issues/38

### CODE REVIEW

**Comment by rwjblue** [comment]
👍 - Thanks for tracking this down!

**Comment by LucasHillDex** [comment]
Should we add that ember-cli-autoprefixer should also run before ember-cli-sri as I think a very similar issue is happening there.

**Comment by cbrevdev** [comment]
Added ember-cli-sri to the before list.

I'm now wondering whether we should also be adding an entry to the broccoli-asset-rev project to be explicitly before ember-cli-sri? Either that, or modify ember-cli-sri to have broccoli-asset-rev be after...

**Comment by kimroen** [comment]
It kind of sounds like we might be missing a logical step in asset generation; both of these want to run after the contents of the assets have "settled", so to speak.

I'm happy to merge these to avoid the issue here, though. Thank you very much!

**Comment by kimroen** [comment]
Thanks again, this has been released as version 0.8.1!

**Pull request merged**
