### PR TITLE
Bump broccoli-autoprefixer to 7.0.0

### PR DESCRIPTION
**Pull request by tansongyang**
This supersedes #40.

### CODE REVIEW

**Comment by tansongyang** [comment]
@kimroen Could you help me understand the build failure? Thanks!

**Comment by jrjohnson** [comment]
It looks like autoprefixer has dropped node v4 support at https://github.com/postcss/autoprefixer/releases/tag/9.0.0 so that should be removed from the tests.

It also looks like the API for broccoli-autoprefixer has changed in https://github.com/sindresorhus/broccoli-autoprefixer/commit/5ff149093d0697b43e127b44bc4b8b34e2c7c0af#diff-0730bb7c2e8f9ea2438b52e419dd86c9

to 
```
const Autoprefixer = require('broccoli-autoprefixer');
tree = new Autoprefixer(tree, options);
```

So https://github.com/kimroen/ember-cli-autoprefixer/blob/master/index.js#L30 needs to be updated as well.

**Comment by tansongyang** [comment]
Hi @jrjohnson , thanks for following up. I believe I made the necessary changes, but it looks like something is still missing.

**Comment by tansongyang** [comment]
Thanks @jrjohnson! I'll keep an eye on it.

**Comment by acorncom** [comment]
@kimroen I'm interested in this change for a client project I'm working on. Would we be able to get a release here at some point?

**Comment by acorncom** [comment]
An update here. I ran @tansongyang's fork locally as part of an app I'm working on and got the following error message:

```sh
<path snipped>/assets/frontend.css.map:3:24: Missed semicolon
  1 | {
  2 | 	"version": 3,
> 3 | 	"file": "frontend.css",
    | 	                      ^
  4 | 	"sourceRoot": "<path snipped>/frontend/app/styles",
  5 | 	"sources": [
```

As I dug in, it looks like this PR may not actually be fully working. I ended up starting a brand new Ember app to test things out and as can be seen in [this reproduction app](https://github.com/acorncom/ember-cli-autoprefixer-repro), things aren't working there either. Interestingly, things fail regardless of use of `.scss` files or not (see my commit messages), so I think there's something else at play.

I also found that this command **might** help us zoom in a bit on seeing the steps that are running shortly before this occurs (but I'm not sure I'm in the right place):
```DEBUG='fast-sourcemap-concat:*' ember s```

**Comment by snewcomer** [comment]
#45 with 1.0.0-beta.0 released!

**Pull request closed without merging**
